### ISSUE TITLE
Windows service: how to log on as "Local Service"

### ISSUE THREAD

**Issue by v1v** [opscode-cookbooks/jenkins#248]
Windows services can be log on as "Local Service" or another user. How do I configure that within the jenkins recipe? As far as I see the jenkins-slave.xml.erb is forcing to use a specific user: https://github.com/opscode-cookbooks/jenkins/blob/master/templates/default/jenkins-slave.xml.erb#L57

It looks serviceaccount is not mandatory from the jenkins point of view: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/windows-service/jenkins.xml
https://github.com/kohsuke/winsw#service-account

It looks a bit odd but from my point of view windows-jenkins-agents should have an optional attribute about the "<serviceaccount>" tag. This is my suggested implementation:

jenkins-slave.xml.erb
```xml
....
<% if is_service_account -%>
    <serviceaccount>
    <%- if @user_domain -%>
       <domain><%= @user_domain %></domain>
    <%- end -%>
       <user><%= @user_account %></user>
    <%- if @user_password -%>
       <password><%= @user_password %></password>
    <%- end -%>
    </serviceaccount>
<% end %>
```

Let me know if you need further scenarios or use cases.

Thanks

**Comment by schisamo** [comment]
@v1v Are you still experiencing issues?

**Comment by schisamo** [comment]
This should have been fixed as part of: https://github.com/opscode-cookbooks/jenkins/pull/376
