### ISSUE TITLE
ssh_slave resource fails to apply the correct credentials

### ISSUE THREAD

**Issue by xeon22** [opscode-cookbooks/jenkins#253]
When supplying a user, and credentials, the resource does not apply the correct credentials to the node object in jenkins.  Somehow it defaults to the first one in the list.

**Comment by schisamo** [comment]
I'm not sure what is happening here. We do have integration test coverage for the case you are describing:
https://github.com/opscode-cookbooks/jenkins/blob/master/test/fixtures/cookbooks/jenkins_slave/recipes/create_ssh.rb#L85-L88

Perhaps you can set the credentials attribute with a static string to rule out some strange attribute overriding of `node['jenkins']['slave']['credentials']`. Closing this for now though. Feel free to re-open if I can lend anymore help.
