### ISSUE TITLE
scripts libraries should be replaced by init.groovy.d/ ?

### ISSUE THREAD

**Issue by xbeta** [opscode-cookbooks/jenkins#281]
Since all scripts are loaded as "post-initialization" step, why wouldn't we just simply put them into init.groovy.d/ instead of executing groovy inline?
In here, I'm referring to this: https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/script.rb

And Jenkins official supported document on this running scripts for master:
https://wiki.jenkins-ci.org/pages/viewpage.action?pageId=70877249

**Comment by schisamo** [comment]
Closing this now because of inactivity. Feel free to open a PR with suggested implementation.
