### ISSUE TITLE
Support --username and --password as parameters to jenkins-cli.jar

### ISSUE THREAD

**Issue by ambientsound** [opscode-cookbooks/jenkins#299]
When security is enabled, and realm is set to UNIX user/group database, it is impossible to use the jenkins cookbook with a UNIX user. This is because private key authentication is disabled, which in turn is due to [JENKINS-22346](https://issues.jenkins-ci.org/browse/JENKINS-22346).

The `jenkins-cli.jar` utility accepts the parameters `--username` and `--password`, which enables the use of a UNIX user again. This functionality is, sadly, not supported by the cookbook.

I kindly ask that you implement this feature, either as parameters to the resources, or similar to the private key variable in `node.run_state[:jenkins_private_key]`.

**Comment by pdaukintis** [comment]
Hi, 

I tried to use your patch (against 2.2.2 version of this cookbook), and can confirm that it works correctly. When node['jenkins']['executor']['cli_credentials'] attribute is set, Chef will use them and successfully authenticate against Jenkins instance.

**Comment by athar03** [comment]
try java -jar jenkins-cli.jar -s http://localhost:8080 who-am-i --username admin --password fe3f1e1624ea4be8873b7a35e28b24be

**Comment by sathizzh** [comment]
should i give my username password each time when I use a command

**Comment by charoleizer** [comment]
No @sathizzh, you could do the login command to be logged:
$ java -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 login --username jenkins --password foobar

**Comment by nageshvkn** [comment]
User -auth:
-auth ram:ram

**Comment by nandakumarpurohit** [comment]
After some trial and errors, got it working by this aliasing statement for jenkins-cli
**alias jenkins-cli='java -jar /var/lib/jenkins/jenkins-cli.jar -auth admin:admin'**

After this aliasing, you can use the commands like:
jenkins-cli help jenkins-cli who-am-i
and many other commands (listed by help)

In my case here, I had added SSH key for 'admin' user of Jenkins and I had changed its password to 'admin'
