### ISSUE TITLE
Is there a way to configure plugin after it is installed

### ISSUE THREAD

**Issue by praste** [opscode-cookbooks/jenkins#301]
Is there a way to configure plugin after it is installed? 
e.g. set MAVEN_HOME, JDK_HOME attributes, or other non-plugin attributes like 'SMTP server'

**Comment by schisamo** [comment]
Groovy is def the right approach. An inline groovy script can be easily executed with the `jenkins_script` resource.

**Comment by praste** [comment]
Only problem is different plugins might have configurations scattered
across different files.

**Comment by schisamo** [comment]
@praste That's why you don't manage/configure the underlying files. You use groovy to perform configuration against the actual Java API. This in turn writes out the files automatically.
