### ISSUE TITLE
Using jenkins_command with an arbitrary endpoint

### ISSUE THREAD

**Issue by jeffb-stell** [opscode-cookbooks/jenkins#302]
Is there a pattern for calling jenkins_command and having it run against an endpoint not set in node['jenkins']['master']['endpoint']? In 1.2.2, it was possible to use the url attribute to jenkins_cli, is there an equivalent now?

**Comment by schisamo** [comment]
@jeffb-stell I suppose the pattern is to set `node['jenkins']['master']['endpoint']` in your recipe before calling `jenkins_command`.

**Comment by schisamo** [comment]
Closing this for now. Feel free to re-open if there is anything else I can do to help.

**Comment by jeffb-stell** [comment]
That's a pretty poor pattern, especially if you are writing a Chef recipe that runs jenkins_command against multiple jenkins servers. Why not add an optional attribute for that, as the 1.2.2 jenkins_cli resource had?

**Comment by schisamo** [comment]
@jeffb-stell Feel free to open a PR with the request/feature you want. It's sometime easier to discussion things over code.
