### ISSUE TITLE
Unable to change lib directory

### ISSUE THREAD

**Issue by pankajmalhotra** [opscode-cookbooks/jenkins#312]
Hi,

In master.rb file I am changing master['home'] to '/sxy/var/lib/jenkins', jenkins is not taking it?
Any idea?

Thanks,
Pankaj

**Comment by fletchowns** [comment]
I also had to relocate the home dir but rather than overriding that attribute value I simply moved the folder and created a symlink from /var/lib/jenkins to the new location:

```
bash "Relocate Jenkins Home" do
  code <<-EOH
    service jenkins stop
    mv #{node['jenkins']['master']['home']} #{new_location}
    ln -s #{new_location}/jenkins #{node['jenkins']['master']['home']}
    service jenkins start
  EOH
  not_if { ::File.exists?("#{new_location}/jenkins") }
end
```

**Comment by schisamo** [comment]
The `node['jenkins']['home']` attribute is really only used by the source/war install:
https://github.com/opscode-cookbooks/jenkins/blob/master/recipes/_master_war.rb#L39-L45

Package-based installs more or less hard code the HOME as part of the package install.
