### ISSUE TITLE
use stable packages

### ISSUE THREAD

**Issue by rmoriz** [opscode-cookbooks/jenkins#314]
It would be nice if we could configure the package install recipe to stick to the stable-packages, e.g.
```http://pkg.jenkins-ci.org/debian-stable/```  instead of: ```http://pkg.jenkins-ci.org/debian/```

Maybe an attribute for the repo-uri would be sufficient?

**Comment by schisamo** [comment]
This will be fixed as part of https://github.com/opscode-cookbooks/jenkins/pull/309
