### ISSUE TITLE
Java flip-flops in /etc/service/jenkins/run

### ISSUE THREAD

**Issue by docwhat** [opscode-cookbooks/jenkins#318]
The `ENV` check should be removed from [attributes/default.rb](https://github.com/opscode-cookbooks/jenkins/blob/master/attributes/default.rb#L45-L53) because when running 'chef-client' from the command line, a different `JAVA_HOME` might be set (or any may be set) from the service.

It has been causing flip-flops (and restarts) on our system if anyone runs `chef-client` by hand.

**Comment by docwhat** [comment]
In addition, by checking `node['java']['java_home']` in `attributes/default.rb` it causes the java cookbook's settings to not take effect until the second run of `chef-client` since the java cookbook wouldn't have had time to run its `set_attributes_from_version` recipe.  Perhaps that should be done in a recipe instead?

**Comment by eheydrick** [comment]
+1

**Comment by schisamo** [comment]
I would recommend explicitly setting `node['jenkins']['java']` in a wrapper recipe or role/environment.
