### ISSUE TITLE
jenkins_jnlp_slave does not create a service on windows

### ISSUE THREAD

**Issue by TeroPihlaja** [opscode-cookbooks/jenkins#321]
When I try to install a jenkins JNLP slave on a Windows Server 2012 R2 it doesn't automatically create a service for the slave.

The slave gets created on Jenkins and I can start it manually with:
java -jar slave.jar -jnlpUrl http://<jenkins>/computer/buildnode2/slave-agent.jnlp -secret <secret>

Is it possible to create the service automatically?

I'm using the following configuration in the recipe:

```
jenkins_jnlp_slave 'buildnode2' do
  remote_fs 'C:/jenkins'
  user      'Administrator'
  group		'Users'
  labels    ['clientvs2013']
end
```

And here's what happens on the chef-client:

```
Recipe: jenkins-build::default
  * jenkins_jnlp_slave[buildnode2] action create
  Recipe: <Dynamically Defined Resource>
    * remote_file[C:\chef\cache/jenkins-cli.jar] action create
      - create new file C:\chef\cache/jenkins-cli.jar
      - update content in file C:\chef\cache/jenkins-cli.jar from none to ac3031

      (new content is binary, diff output suppressed)
      - change dacl
    * remote_file[C:\chef\cache/update-center.json] action create_if_missing
      - create new file C:\chef\cache/update-center.json
      - update content in file C:\chef\cache/update-center.json from none to 758
5fc
      - suppressed sensitive resource
      - change dacl
    * file[C:\chef\cache/extracted-update-center.json] action create
      - create new file C:\chef\cache/extracted-update-center.json
      - update content in file C:\chef\cache/extracted-update-center.json from n
one to 11690a
      - suppressed sensitive resource
      - change dacl
    * file[C:\chef\cache/jenkins-key] action create
      - create new file C:\chef\cache/jenkins-key
      - update content in file C:\chef\cache/jenkins-key from none to 72c58a
      - suppressed sensitive resource
    - Create jenkins_jnlp_slave[buildnode2]
    * directory[C:/jenkins] action create (up to date)
    * directory[C:/jenkins] action create
      - change owner
      - change group
  Recipe: runit::default
    * service[runit] action nothing (skipped due to action :nothing)
    * execute[start-runsvdir] action nothing (skipped due to action :nothing)
    * execute[runit-hup-init] action nothing (skipped due to action :nothing)
    - evaluate block and run any associated actions
  Recipe: <Dynamically Defined Resource>
    * remote_file[C:/jenkins/slave.jar] action create
      - create new file C:/jenkins/slave.jar
      - update content in file C:/jenkins/slave.jar from none to 28a1e8
      (new content is binary, diff output suppressed)
      - change dacl

  * service[jenkins-slave] action nothing (skipped due to action :nothing)
```

**Comment by carpnick** [comment]
You are right - The docs are a bit out of date, in my opinion.  I have a PR to get some of the windows functionality fixed: https://github.com/opscode-cookbooks/jenkins/pull/323

With this change and using the corrected documentation.  I was able to get a windows slave provisioned.  
Note - because you are running a windows service, whichever user you select in your recipe needs a logon as a service right.  If you push that through the domain ignore the rest of this comment.

Winsw - which chef uses on Windows -doesnt have this natively.  Added a PR for that here: https://github.com/kohsuke/winsw/pull/64

**Comment by schisamo** [comment]
@TeroPihlaja you want to use the `jenkins_windows_slave` resource.

**Comment by TeroPihlaja** [comment]
The reason I decided to use jenkins_jnlp_slave instead was that I didn't have to put the user password in the cookbook. Also the documentation seems to be bit out of date. The only mention of jenkins_windows_slave is in an example but it's not explained anywhere.
