### ISSUE TITLE
question on authentication

### ISSUE THREAD

**Issue by dpetzel** [opscode-cookbooks/jenkins#328]
While fighting with getting authentication using github oauth, I've been over this snippet from the readme a number of times:

> This means that if you have LDAP or GitHub OAuth based authn/authz enabled the user you are using for configuraiton tasks must have an associated account in the external services. Please see JENKINS-22346 for more details.

Does this say you would need to run chef as the user that exists in github, or is there some way of telling the cookbook to use some alternate user when `executor` is invoked?.

So far I've been unable to get this to work on recent versions of Jenkins. Downgrading to 1.555 works as mentioned in `JENKINS-22346`, but is obviously not ideal. I'd love to figure out how to get the authentication piece working on newer versions.

**Comment by acqant** [comment]
I'm dealing with this myself too.  Very unclear what needs to be done where based on what else is set where.

**Comment by erichelgeson** [comment]
It means that if you had this user that interacts with the jenkins api
```ruby
jenkins_user 'chef' 
```
and did github authentication, a user named `chef` needs to exist on github as well. You should probably create a service account on github for your jenkins to use.

**Comment by dpetzel** [comment]
That lone is not enough (I did that). I have jenkins user that matches my github user. How do you specify the `user you are using for configuraiton tasks`. I don't see any way to tell Chef "run the jenkins configuration tasks as user x". Chef is running as root, and it seems (although I admit I am not sure) its using some sort of built in default and I don't see a way to tell Chef to use some other user for this.

**Comment by acqant** [comment]
dpetzel:  I think you need to set the run_state with the ssh key "stuff"

Mine is working as such:

I add a local 'jenkins' user with ssh key like the README.md has
I set ldap security relm and matrix authorization.  
I added the jenkins user to Admin role and jenkins_group ( ldap group ) to Admin role.
I use the run_state with the local jenkins user and ssh key.
That seems to allow the CLI to run groovy scripts.

BUT!  I don't see how the run_state is authorizing the local jenkins user.  I think the local jenkins user uses the CLI with the ssh key and jenkins just queries my ldap server to see if the user exists and what groups it has.

**Comment by erichelgeson** [comment]
@dpetzel thanks for the clarification 

Also there is now an option to allow non existen users to login 

> What's new in 1.604 (2015/03/15)
>  Added a switch (-Dhudson.model.User.allowNonExistentUserToLogin=true) to let users login even when the record is not found in the backend security realm. (issue 22346)

**Comment by schisamo** [comment]
@dpetzel regarding:

> I don't see any way to tell Chef "run the jenkins configuration tasks as user x". Chef is running as root, and it seems (although I admit I am not sure) its using some sort of built in default and I don't see a way to tell Chef to use some other user for this.

Jenkins attempts to match the private key you provide to the CLI to a user with a matching public key.

Here at Chef Software, Inc. we have the following in our wrapper cookbook:

```ruby
jenkins_users = encrypted_data_bag_item_for_environment('jenkins', 'users')

node.run_state[:jenkins_private_key] = jenkins_users['chef-jenkins']['private_key']

# Create a Jenkins user for Chef to authenticate with for configuration
# activities
jenkins_user 'chef-jenkins' do
  full_name 'Chef Jenkins User'
  public_keys [jenkins_users['chef-jenkins']['public_key']]
end
```

If you want to take advantage of the new `-Dhudson.model.User.allowNonExistentUserToLogin=true` option that @erichelgeson mentioned I believe you will need the changes that are part of https://github.com/opscode-cookbooks/jenkins/pull/355.

**Comment by schisamo** [comment]
Closing this for now as it should no longer be an issue. If after testing master/HEAD this issue persists feel free to re-open.
