### ISSUE TITLE
jenkins-config-rhel.erb Bug?

### ISSUE THREAD

**Issue by choih** [opscode-cookbooks/jenkins#332]
Jenkins default username is defined in attributes/master.rb and therefore this value can be customized.

However, jenkins-config-rhel.erb redefines JENKINS_USER as hard-coded value "jenkins".  So if I install Jenkins as a different user, the service would fail to start because "jenkins' user cannot be found.

Can you confirm if this is a bug?  

Shouldn't JENKINS_USER variable in jenkins-config-rhel.erb use the value from attribute/master.rb such as node['jenkins']['master']['user'] instead?

**Comment by schisamo** [comment]
@choih When you install Jenkins via one of the packages the user is determined by the package (which also creates said user). The attribute you referenced is used by WAR installs which run under Runit.
