### ISSUE TITLE
Chef 12: WARN: The on_platforms option to node_map has been deprecated

### ISSUE THREAD

**Issue by rvelaz** [opscode-cookbooks/jenkins#335]
When running rspec tests for a recipe that includes jenkins::master, I get the following warning:

WARN: The on_platforms option to node_map has been deprecated

- Command: `chef exec rspec`
- OS: OS X 10.10
- Cookbook Version: 2.2.2
- Ruby Version: ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin14.0]
- Rubygems Version: 2.4.6
- Chef Version: Chef: 12.0.3
- env:
    ```text
    rvm_bin_path=/Users/user_1/.rvm/bin
GEM_HOME=/Users/user_1/.rvm/gems/ruby-2.1.0
TERM=xterm
SHELL=/bin/bash
IRBRC=/Users/user_1/.rvm/rubies/ruby-2.1.0/.irbrc
TMPDIR=/var/folders/1n/vlkdthvx7j3c5nwxm6pnrxfr0000gn/T/
MY_RUBY_HOME=/Users/user_1/.rvm/rubies/ruby-2.1.0
USER=user_1
_system_type=Darwin
rvm_path=/Users/user_1/.rvm
rvm_prefix=/Users/user_1
PATH=/Users/user_1/.rvm/gems/ruby-2.1.0/bin:/Users/user_1/.rvm/gems/ruby-2.1.0@global/bin:/Users/user_1/.rvm/rubies/ruby-2.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/Users/user_1/.rvm/bin
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home
LANG=en_GB.UTF-8
_system_arch=x86_64
XPC_FLAGS=0x0
_system_version=10.10
XPC_SERVICE_NAME=0
rvm_version=1.26.10 (latest)
SHLVL=1
COLORFGBG=7;0
HOME=/Users/user_1
LOGNAME=user_1
GROOVY_HOME=/usr/local/opt/groovy/libexec
GEM_PATH=/Users/user_1/.rvm/gems/ruby-2.1.0:/Users/user_1/.rvm/gems/ruby-2.1.0@global
RUBY_VERSION=ruby-2.1.0
_system_name=OSX
_=/usr/bin/env
    ```
- Backtrace:
    ```text
    Create a recipe with:
include_recipe 'jenkins::master'

Then create rspec file:
require 'chefspec'
require 'chefspec/berkshelf'

describe 'cookbook::recipe' do
  let(:chef_run) {
    ChefSpec::SoloRunner.new.converge(described_recipe)
  }

    it "Should include recipe jenkins::master" do
      expect(chef_run).to include_recipe('jenkins::master')
  end
end

**Comment by schisamo** [comment]
I'm not seeing this using the latest version of ChefDK (currently 0.5.1) for testing. Please switch over to using ChefDK. We have even updated the Travis job to take advantage of ChefDK:
https://travis-ci.org/opscode-cookbooks/jenkins/builds/62321152

**Comment by rvelaz** [comment]
Hi Seth,
Thanks for getting back on this. I've upgraded to 0.5.1 and still see the
issue. I have uploaded an example where it happens to:
https://github.com/rvelaz/chef_test

#chef exec rspec
[2015-05-15T08:18:18+02:00] WARN: The on_platforms option to node_map has
been deprecated
.

Finished in 0.52788 seconds (files took 6.28 seconds to load)
1 example, 0 failures

#chef --version
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0

Thanks,



2015-05-13 1:51 GMT+02:00 Seth Chisamore <notifications@github.com>:

**Comment by chazzly** [comment]
I ran into the same issue and found the culprit.  I submitted PR #414 to address it.
