### ISSUE TITLE
Windows Slave HWRP should use 'service' resource

### ISSUE THREAD

**Issue by btm** [opscode-cookbooks/jenkins#336]
The windows slave hwrp in ```libraries/slave_windows.rb``` creates a service resource by creating a Chef::Resource::Service object, but the windows service provider now has attributes that the service resource doesn't have. This could be fixed by using Chef::Resource::WindowsService instead, but we should instead just use the ```service``` resource directly so the resource and provider resolvers in core can pick the right resources and providers.

https://github.com/chef/chef/issues/3071

**Comment by schisamo** [comment]
I think we'll just need to switch to `Chef::Resource::WindowsService`. The reason we can't use the `service` resource directly is we don't want the resource to execute an action at the point it's instantiated, instead `run_action` is called in the parent class:
https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave_jnlp.rb#L67

**Comment by btm** [comment]
As discussed in the hallway, this would be best: 

@service_resource = Chef::Resource.resource_for_node(:service, node).new(new_resource.service_name, run_context)
