### ISSUE TITLE
expose https and http as attributes for SSL/HTTPS support

### ISSUE THREAD

**Issue by acqant** [opscode-cookbooks/jenkins#339]
It was pretty easy to get jenkins to listen on 8433 and install a pem and key file all by hand.
It doesn't look like you can manipulate the /etc/sysconfig/jenkins on a redhat box with this cookbook is that correct?

Magic command line options

--httpPort=-1 --httpListenAddress=0.0.0.0  --httpsCertificate=/etc/pki/tls/certs/my.crt --httpsPrivateKey=/etc/pki/tls/certs/my.key --httpsPort=8443

**Comment by acqant** [comment]
Could use a little direction on next steps here.
I've added the attributes and added the changes to the svc and runit templates.

I'd like to disable http with -1 option but I'm not sure how/if that will break tests.

https://github.com/opscode-cookbooks/jenkins/compare/master...acqant:master

**Comment by schisamo** [comment]
As I mentioned in https://github.com/opscode-cookbooks/jenkins/pull/340#issuecomment-101391730 we are not going to add this feature to this cookbook. To keep things simple, we would prefer this type of config be done using an HTTP proxy like Nginx or Apache in front of the Jenkins instance. This could easily be implemented in a wrapper cookbook that uses the jenkins cookbook. As such I'm closing this PR.
