### ISSUE TITLE
Plugin install timeout

### ISSUE THREAD

**Issue by dpnl87** [opscode-cookbooks/jenkins#343]
I'm trying to use the jenkins_plugin LWPR to install some needed plugins. When running ```kitchen converge``` it keeps timing out in the installation of the first plugin.

I have tried to increase the ```node.set['jenkins']['executor']['timeout']``` to 480 seconds but without success.

When tailing the logs it seems the LWPR can't connect to the plugins center to install the plugin. As I don't see any log lines during the failing run. When I try to install the plugin with the GUI I do get log lines.

What am I doing wrong here?

```
jenkins_plugin 'greenballs' do
  version '1.4'
  notifies :restart, 'runit_service[jenkins]', :immediately
end
```

```
===============================================================================
Error executing action `install` on resource 'jenkins_plugin[greenballs]'     
===============================================================================

Jenkins::Helper::JenkinsNotReady
--------------------------------
The Jenkins master at `http://localhost:8080' did not become ready within 60
seconds. On large Jenkins instances, you may need to increase the timeout to
240 seconds. Alternatively, Jenkins may have failed to start.
Jenkins can fail to start if:

  - a configuration file is invalid
  - a plugin is only partially installed
  - a plugin's dependencies are not installed

If this problem persists, check your Jenkins log files.

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:360:in `rescue in wait_until_ready!'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:340:in `wait_until_ready!'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/_helper.rb:427:in `ensure_update_center_present!'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:362:in `plugin_universe'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:252:in `install_plugin_from_update_center'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:124:in `block (2 levels) in <class:JenkinsPlugin>'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:137:in `call'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:137:in `block (2 levels) in <class:JenkinsPlugin>'
/tmp/kitchen/cache/cookbooks/jenkins/libraries/plugin.rb:151:in `block in <class:JenkinsPlugin>'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/eet_jenkins_ag_role/recipes/master.rb

 29: jenkins_plugin 'greenballs' do
 30:   version '1.4'
 31:   notifies :restart, 'runit_service[jenkins]', :immediately
 32: end
```

**Comment by iankendrick** [comment]
The timeout is coming from your jenkins service, not update center. Make sure you have included jenkins::master before any other jenkins LWRP and that jenkins is starting successfully (by running 'curl http://localhost:8080/').

If you are running jenkins on a non-standard port/IP, you'll need to set the jenkins['master']['endpoint'] attribute.

**Comment by dpnl87** [comment]
Thank you @iankendrick :+1:

The issue was that Test Kitchen somehow was showing a 404 on http://localhost:8080 and had to set the endpoint to http://localhost:8080/jenkins

**Comment by rudijs** [comment]
+1 thanks @iankendrick 

I have Graphite running on port 8080 already so I set Jenkins to run on port 8081.

As @iankendrick points out the endpoint then also needs to be updated.

So my Jenkins wrapper cookbook default attributes has these:

    default['jenkins']['master']['port'] = 8081
    
    # As Jenkins is not running the default port of 8080, need to update the Jenkins endpoint
    default['endpoint'] = "http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}"
