### ISSUE TITLE
Manipulating the init script

### ISSUE THREAD

**Issue by daften** [opscode-cookbooks/jenkins#344]
Hi,

I'd need a possibility to manipulate the startup script. For 2 reasons:
1. Manipulating the PATH by chef. I need to be able to set the PATH for jenkins from the chef cookbook I use to provision the server.
2. Using chruby. I want chruby on the server to be able to run multiple ruby versions and use bundle install and bundle exec commands (from within a phing execution in a jenkins job). For this to work properly, I think I'll need to add this line to jenkins init: "source /usr/local/share/chruby/chruby.sh"

If I'm on the wrong path, please point me in the right direction. If this is the right way, I think the general jenkins cookbook should or could provide a mechanism to manipulate the init script in a structured way.

**Comment by schisamo** [comment]
@daften You should create a 'wrapper' cookbook that sets these sorts of things up.

Assuming you have a wrapper cookbook named `yourcompany-jenkins` you could have a main recipe as simple as:

```ruby
include_recipe 'jenkins::master'

# Tell Chef to use your personal copy of the main Runit init script
init_script = resources(template: '/etc/sv/jenkins/run'
init_script.cookbook 'yourcompany-jenkins'
```

You could then copy [sv-jenkins-run.erb template from this Jenkins cookbook](https://github.com/opscode-cookbooks/jenkins/blob/master/templates/default/sv-jenkins-run.erb) into `yourcompany-jenkins` at `templates/default/sv-jenkins-run.erb` and modify as you see fit.

**Comment by schisamo** [comment]
Closing this now. Feel free to re-open if I can help in any other way.

**Comment by daften** [comment]
Hi @schisamo, I don't understand how your code would work, the template filename isn't mentioned anywhere there, can you explain that more for me please? Or point me to a page in the chef documentation, because I can't find it.

Thanks! :)

**Comment by daften** [comment]
Or maybe equivalent code in this cookbook?

**Comment by schisamo** [comment]
@daften It's how Runit and the Runit cookbook work:
http://smarden.org/runit/
https://github.com/hw-cookbooks/runit/

Runit init scripts are written out to `/etc/sv/SERVICE_NAME/run`. The Runit cookbook uses the convention of naming the ERB for template as `sv-SERVICE_NAME-run.erb`:
https://github.com/hw-cookbooks/runit/blob/develop/libraries/provider_runit_service.rb#L47-L55

**Comment by daften** [comment]
OK, but I guess I still need to add a template section to my cookbook as well to get this to work?
There is no template for /etc/sv/jenkins/run in this cookbook btw :)

**Comment by schisamo** [comment]
@daften There is:
https://github.com/opscode-cookbooks/jenkins/blob/master/templates/default/sv-jenkins-run.erb

You will just drop that template in your wrapper cookbook and make the changes you want. You then add this to your wrapper recipe to force Chef to prefer your copy of the template:

```ruby
# Tell Chef to use your personal copy of the main Runit init script
init_script = resources(template: '/etc/sv/jenkins/run')
init_script.cookbook 'yourcompany-jenkins'
```
