### ISSUE TITLE
jenkins::java to set node['jenkins']['java']

### ISSUE THREAD

**Issue by epcim** [opscode-cookbooks/jenkins#352]
The recipe `jenkins::java` should eat what he cooked. So if the recipe is used to install open-jdk it should set it as a default java for jenkins using:
```
node.set['jenkins']['java']
```
or do some OS cfg.. like update-alternatives --set java <openjdk java path> (on ubuntu)

**Comment by schisamo** [comment]
In most cases `java` should just be picked up from `PATH`. You only need to override `node['jenkins']['java']` if you are using a Java installed a an alternate location.

Also please read the documentation on in the `jenkins::java` recipe:
https://github.com/opscode-cookbooks/jenkins/blob/master/recipes/java.rb#L21-L33

That recipe exists mostly to support the integration tests you should install Java in a way that makes the most sense for you company.

**Comment by schisamo** [comment]
Closing this for now. Feel free to re-open if my response doesn't satisfy you.
