### ISSUE TITLE
since v2.3.0: undefined method `lazy' for Chef::Resource::JenkinsCredentials:Class

### ISSUE THREAD

**Issue by philicious** [opscode-cookbooks/jenkins#358]
I get error like 
```
     NoMethodError:
       undefined method `lazy' for Chef::Resource::JenkinsCredentials:Class
     # /var/folders/mv/yjh_dxgj69g85ms14_1wlrwm0000gp/T/d20150515-47465-62s4vu/cookbooks/jenkins/libraries/credentials.rb:53:in `<class:JenkinsCredentials>'
```

~~since mixlib-config 2.2.0 and 2.2.1. before I had 2.1.0 and it was fine.~~

~~I'm not sure if this is a mixlib bug or if jenkins cookbook should pin down the version or fix its specs.
Therefore I reported it also here https://github.com/chef/mixlib-config/issues/29~~

**Comment by schisamo** [comment]
What version of Chef are you using?

**Comment by philicious** [comment]
```
1# chef-client -v
Chef: 11.16.4
```

**Comment by philicious** [comment]
chefspec is pinned to ~>3.4 if that matters.

**Comment by philicious** [comment]
after some testing and comparing previous builds, the problem is with jenkins cookbook v2.3.0. v2.2.2 doesnt have that error, no matter what mixlib-config version. (its version also updated for the first failing build so I was mislead)

**Comment by bixu** [comment]
I'm also seeing this with versions of the cookbook after 2.2.0

**Comment by schisamo** [comment]
Any chance y'all can upgrade to Chef 12+? This issue was fixed with the 12.0.0 release: https://github.com/chef/chef/pull/1559

I removed the workaround we had been carting around which was causing issues with recent versions of Chef 12: https://github.com/opscode-cookbooks/jenkins/commit/35cee51bdd44e35baba5dab8402badbdd74bf3be

**Comment by bixu** [comment]
I'll try to do some testing to see if we can update without exploding things.  IIRC there was an issue with 12+ that was holding us back.

**Comment by philicious** [comment]
updating to Chef12 is not an option for us at the very moment. but for me it would be ok to stay at 2.2.0 I guess

**Comment by bixu** [comment]
It seems to me that if chef-client has to be bumped a major version for this cookbook to work, then the java cookbook should be versioned to 3+ to signify a breaking change?

**Comment by schisamo** [comment]
@philicious @bixu Can you give https://github.com/opscode-cookbooks/jenkins/pull/362 a go?
