### ISSUE TITLE
Should "jenkins_windows_slave" resource automatically add user to "Log on as a service" Security Policy?

### ISSUE THREAD

**Issue by chico-san** [opscode-cookbooks/jenkins#374]
Recently made use of "jenkins_windows_slave" with a local account on the machine (created via the same windows jenkins slave recipe) to start the jenkins slave service.

Had to do some powershell script in recipe to change "Security Settings" -> "User Rights Assignment" -> "Log on as a service" policy setting to add this local jenkins account, in order for the jenkins slave service to start properly as this "jenkins" local user.

The https://github.com/opscode-cookbooks/windows cookbook does not have a resource to manipulate Local Security Policy, perhaps "jenkins_windows_slave" resource should do this automatically if "user" attribute is set?

**Comment by carpnick** [comment]
Hey @chico-san  - See PR just referenced.  Solved this from the winsw perspective.

**Comment by schisamo** [comment]
Fixed as part of https://github.com/opscode-cookbooks/jenkins/pull/376.

**Comment by chico-san** [comment]
sweet!  Thanks!
