### ISSUE TITLE
Problem comparing some jenkins plugin versions

### ISSUE THREAD

**Issue by maoueh** [opscode-cookbooks/jenkins#380]
I wanted to update our Jenkins `junit` plugin from version `1.2-beta-4` to version `1.6` but it failed with this error:

    ArgumentError: comparison of String with Gem::Version failed

It seems the previous version was turned into a `String` because being an invalid `Gem::Version` while the desired version was parsed as a `Gem::Version` object. This breaks comparison as the two arguments are not of the right type.

My idea to fix this would be to use a custom comparison function `plugin_upgrade?` that fallback to String comparison on `ArgumentError`. PR on its way.

Regards,
Matt

**Comment by schisamo** [comment]
Fixed as part of https://github.com/opscode-cookbooks/jenkins/pull/381
