### ISSUE TITLE
Abstracting Package Repository Information

### ISSUE THREAD

**Issue by pantocrator27** [opscode-cookbooks/jenkins#385]
I have a use case where by I am behind a corporate proxy.

What I would like to do is to be able to mirror the Jenkins repositories internally, then use this cookbook to install them by changing its repository attributes.  

Would it make sense to be able to separate out the repository definition into its own separate cookbook similar to how the yum-* repos are defined?

That would enable this use case.  Thanks in advance!

**Comment by schisamo** [comment]
I would recommend just creating your own version of `jenkins:: _master_package` in a wrapper cookbook. You can then take advantage of all the resources that ship in this cookbook to manage your Jenkins installation.
