### ISSUE TITLE
When using foodcritic, an error is thrown, fixing it, makes the cookbook fail

### ISSUE THREAD

**Issue by daften** [opscode-cookbooks/jenkins#388]
For authenticated jenkins, i set the run_state of the node, like it says in the README. However, doing it like that gives an error with foodcritic:
```FC001: Use strings in preference to symbols to access node attributes```
If I fix that error and use node.run_state['jenkins_private_key'] instead of node.run_state[:jenkins_private_key], my cookbook fails. Any idea why?

**Comment by pagnmickie** [comment]
I'm wondering this myself.

**Comment by carpnick** [comment]
based on this line: https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/_helper.rb#L213

Looks like you should be doing this instead:
node['jenkins']['executor']['private_key']=THE_KEY

However it looks like there is a built in warning when you do that

**Comment by schisamo** [comment]
Yeah this is a bug in Foodcritic. We do this in our wrapper cookbook:

```ruby
node.run_state[:jenkins_private_key] = jenkins_users['chef-jenkins']['private_key'] # ~FC001
```
