### ISSUE TITLE
jenkins_cli username/password

### ISSUE THREAD

**Issue by jsmickey** [opscode-cookbooks/jenkins#391]
I manage a Jenkins installation using LDAP authentication.  I would like to take advantage of jenkins_cli username/password within the cookbook.

I see commits for this here: https://github.com/opscode-cookbooks/jenkins/commit/5eead2ae32daec3b2eea04ce87b19e1c21d3ecf0

But when I browse master, I do not see those changes.  Were they reverted?   In master, I see no changes to attibutes/executor.rb since the original commit in 2014.

**Comment by yzl** [comment]
@jsmickey They're accessed via the `run_context` now:  https://github.com/opscode-cookbooks/jenkins/commit/8980fda798f5ca7ca9c6529152146ba63fc63af5

**Comment by jsmickey** [comment]
@yzl Thank you.  I was able to get this working with LDAP.  The documentation through me off with the warning that PAM was the only authentication method that would work with username/password

I am going to submit a pull request with a readme update
