### ISSUE TITLE
Cannot upgrade from Junit plugin 1.2-beta-4

### ISSUE THREAD

**Issue by FreakyDug** [opscode-cookbooks/jenkins#393]
When I try to use chef to update the default Junit plugin in Jenkins 1.609.1 (1.2-beta-4) to 1.8, I get the following message:

- Upgrade jenkins_plugin[junit] from 1.2-beta-4 to 1.8

However, the Jenkins UI shows 1.2-beta-4 is still installed and when I run chef again I get the same message again.

After I manually upgraded to 1.3, chef happily upgraded it to 1.8.

**Comment by schisamo** [comment]
I think this was fixed as part of https://github.com/opscode-cookbooks/jenkins/pull/381. Can you give the latest code from master a try?

**Comment by FreakyDug** [comment]
I updated to the new 2.4.0 release and that fixed the problem. Thanks!
