### ISSUE TITLE
jenkins_plugin appears to do nothing?

### ISSUE THREAD

**Issue by akl32** [opscode-cookbooks/jenkins#394]
I am trying to use a Chef recipe, in AWS ops-works, to install the git and github plugins on my Jenkins instance. (The instance was successfully created using the jenkins::master recipe.) My cookbook is called jenkins_crm; it contains a metadata.rb file with `depends 'jenkins'` and one recipe called `install_plugins.rb` with two `jenkins_plugin 'plugin_name'` lines. The log says

> [2015-08-17T20:15:00+00:00] INFO: Processing jenkins_plugin[git] action install (jenkins_crm::install_plugins line 1)
> [2015-08-17T20:15:00+00:00] INFO: Processing remote_file[/var/lib/aws/opsworks/cache.stage2/update-center.json] action create (dynamically defined)
> [2015-08-17T20:15:01+00:00] INFO: Processing file[/var/lib/aws/opsworks/cache.stage2/extracted-update-center.json] action create (dynamically defined)
> [2015-08-17T20:15:02+00:00] INFO: Processing jenkins_plugin[github] action install (jenkins_crm::install_plugins line 2)

then moves onto other tasks. It does indeed create the update-center.json and extracted-update-center.json, but does not (it seems) download the plugin. Any idea what's going on? The Jenkins system log shows update center being updated but doesn't show the plugin being installed. And needless to say, the plugins don't actually get installed.

What am I doing wrong? Any help would be appreciated!

**Comment by carpnick** [comment]
This is how we call it internally. Just giving you an example  of some place I know it works.  Using Jenkins version : 1.596-1.1
```
jenkins_plugin "#{cookbook_name}_jenkins_plugin_git" do
  name 'git'
  version '2.3.4'
	install_deps true
	action [:install]
	notifies :restart, 'service[jenkins]', :immediately
end
```

**Comment by akl32** [comment]
Thanks! I wiped my Jenkins instance and tried again and it worked. Not sure what was going on.
