### ISSUE TITLE
NullPointerException when slave has no node/slave properties on Create/Online action

### ISSUE THREAD

**Issue by carpnick** [opscode-cookbooks/jenkins#396]
Environment:
RHEL 6.5 using LTS Jenkins version: 1.609.2
Master at [latest commit on 9/1](https://github.com/opscode-cookbooks/jenkins/tree/159398823af39f085f33c169801901b7d0171f07)

Slave LWRP call:
```
require "socket"
jenkins_jnlp_slave "#{Socket.gethostname()}" do
  description     'Runs any linux oriented tasks'
  remote_fs       '/home/jenkins'				
  executors       3
  usage_mode      'normal'
  availability    'always'	
  labels          ['linux', 'chef-stable', 'gembuilder']
  retries         3 
  action  [:create, :online]
end

```

Generates the following [groovy script](https://gist.github.com/carpnick/3f72bb3b127d6c07f8b0) as part of the LWRP call.

[This](https://gist.github.com/carpnick/3f72bb3b127d6c07f8b0#file-gistfile1-txt-L19) line fails.  Doing a bit more investigation this line below returns null:
```
slave.nodeProperties.get(EnvironmentVariablesNodeProperty.class)?.envVars
```
So when a call to ``` new java.util.HashMap<String,String>()```` takes in null we get a [NullPointerException via LWRP](https://gist.github.com/carpnick/3a1c0c4640da7764e0e4)

Workaround is to call the LWRP this way
```
require "socket"
jenkins_jnlp_slave "#{Socket.gethostname()}" do
  description     'Runs any linux oriented tasks'
  remote_fs       '/home/jenkins'				
  executors       3
  usage_mode      'normal'
  availability    'always'	
  labels          ['linux', 'chef-stable', 'gembuilder']
 environment(
    a: 'a'
  )
  retries         3 
  action  [:create, :online]

end
```

FYI @mcallb 

I think the fix is to [look at this line](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave.rb#L334) and do a null if check

I will look at doing a PR for it.

**Comment by ifel** [comment]
Thank you for logging this issue. I've created a fix for this https://github.com/opscode-cookbooks/jenkins/pull/397

Would you please test it?

**Comment by schisamo** [comment]
Fixed as part of https://github.com/opscode-cookbooks/jenkins/pull/397
